### ISSUE TITLE
while, if-else

### ISSUE THREAD

**Issue by Hikarunnie** [Hikarunnie/FOP-project#7]
i finished writing if-else interpreter but for some reason there are few issues about it. mari i think your  while loops condition evaluation is not as correct as it seems, so ill try to fix it and ill commit it all tomorrow

**Comment by Mariammm870** [comment]
I checked my code on other algorithms and you're right, there are some mistakes

**Comment by Mariammm870** [comment]
So i fixed my code, made some changes in eval, now my code works well.

**Comment by Hikarunnie** [comment]
perfect!  commit your changes

**Comment by Hikarunnie** [comment]
ori damatebiti methodis shemotana momiwia but anyways

**Comment by Hikarunnie** [comment]
officially fixed  ><
